[package]
name = "monkey"
version = "0.2.0"
authors = ["Furkan <furkan.turkal@hotmail.com>"]
edition = "2018"
keywords = ["interpreter"]
license = "MIT"

[dependencies]
byteorder = "1.3.4"

[[bin]]
name = "benchmark"
path = "src/benchmark.rs"
